---
driver:
  name: vagrant
  network: 
    - ["private_network", {ip: "192.168.45.43"}]
provisioner:
  name: chef_solo

platforms:
- name: sbeliakou/centos-7.4-x86_64-minimal
  # driver_config:
  #   box: cloud-ubuntu1204
  #   box_url: https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: default
    run_list:
      - recipe[jboss7::default]
    attributes:
